# Generated by Django 4.0.3 on 2022-04-06 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_acc', '0004_appuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='You must enter a valid phone number', regex='^\\+?(?P<phone>(\\d{8,15}))$')]),
        ),
    ]
