# Generated by Django 4.0.3 on 2022-04-06 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_acc', '0005_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.RegexValidator('^\\+?(?P<phone>(\\d{8,15}))$', message='You must enter a valid phone number')]),
        ),
    ]
