# Generated by Django 4.0.3 on 2022-04-14 23:00

import My_final_social_media_shop.auth_acc.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_acc', '0008_alter_appuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[My_final_social_media_shop.auth_acc.validators.gmail_validator]),
        ),
    ]
