# Generated by Django 4.0.1 on 2022-01-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='job_title',
            field=models.CharField(choices=[('1', 'Software Developer'), ('2', 'QA Engineer'), ('3', 'DevOps Specialist')], default='No Choice', max_length=20),
        ),
    ]
