# Generated by Django 4.0.1 on 2022-01-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.CharField(choices=[('Google', 'Google'), ('Soft Uni', 'Soft Uni')], default='Soft Uni', max_length=8),
            preserve_default=False,
        ),
    ]
