# Generated by Django 4.0.1 on 2022-01-31 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ('first_name',)},
        ),
        migrations.AddField(
            model_name='testmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-27'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testmodel',
            name='update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
