# Generated by Django 4.0.1 on 2022-02-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_delete_testmodel_department_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
