# Generated by Django 4.0.3 on 2022-03-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_acc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
    ]
