# Generated by Django 4.0.2 on 2022-02-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='exercises',
            field=models.ManyToManyField(to='exercise_app.DoneExercise'),
        ),
    ]
