# Generated by Django 4.0.4 on 2022-04-30 12:52

import CarAPI.cars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Car Brand'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Car Model'),
        ),
        migrations.AlterField(
            model_name='usercar',
            name='first_reg',
            field=models.CharField(max_length=25, validators=[CarAPI.cars.validators.only_letters_and_nums]),
        ),
    ]
