# Generated by Django 4.0.2 on 2022-02-24 17:37

import django.core.validators
from django.db import migrations, models
import prep2.tracker.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('expense_image', models.URLField()),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), prep2.tracker.models.only_char])),
                ('last_name', models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), prep2.tracker.models.only_char])),
                ('budget', models.FloatField(default=0, validators=[prep2.tracker.models.bigger_than_0])),
                ('profile_image', models.ImageField(blank=True, default='static/images/user.png', null=True, upload_to='images', validators=[prep2.tracker.models.MaxSizeFile(5)])),
            ],
        ),
    ]
