# Generated by Django 4.0.2 on 2022-02-24 18:25

from django.db import migrations, models
import prep2.tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images', validators=[prep2.tracker.models.MaxSizeFile(5)]),
        ),
    ]
