# Generated by Django 4.0.3 on 2022-03-29 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Outwear', 'Outwear'), ('Hoodies and Sweatshirts', 'Hoodies and Sweatshirts'), ('Jeans', 'Jeans'), ('T-shirts', 'T-shirts'), ('Joggers', 'Joggers')], max_length=23),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
