# Generated by Django 4.0.3 on 2022-04-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_send_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
