# Generated by Django 4.0.3 on 2022-04-03 13:38

import My_final_social_media_shop.marketplace.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_orderitem_purchased_orderitem_user_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='media/products/', validators=[My_final_social_media_shop.marketplace.validators.MaxSizePhotoValidator(5)]),
        ),
    ]
