# Generated by Django 4.0.3 on 2022-04-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
