# Generated by Django 4.0.3 on 2022-04-06 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0010_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
