# Generated by Django 4.0.3 on 2022-04-15 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_alter_order_billing_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='purchased',
        ),
    ]
