# Generated by Django 4.0.3 on 2022-04-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_remove_orderitem_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
