# Generated by Django 4.0.3 on 2022-04-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0015_orderitem_purchased'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='purchased',
        ),
    ]
