# Generated by Django 4.0.2 on 2022-02-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
