# Generated by Django 4.0.2 on 2022-02-23 10:00

from django.db import migrations, models
import ws_exercise.petstagram.models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0002_alter_profile_gender_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[ws_exercise.petstagram.models.MaxSizePhoto(5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('date_time_published', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('tagged_pets', models.ManyToManyField(to='petstagram.Pet')),
            ],
        ),
    ]
