# Generated by Django 4.0.2 on 2022-02-23 18:54

from django.db import migrations, models
import ws_exercise.petstagram.models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0003_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='mediafiles', validators=[ws_exercise.petstagram.models.MaxSizePhoto(5)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
