# Generated by Django 4.0.2 on 2022-02-06 16:11

import django.core.validators
from django.db import migrations, models
import workshop1.petstagram.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, validators=[django.core.validators.MinValueValidator(2), workshop1.petstagram.validators.validate_only_letters])),
                ('last_name', models.CharField(max_length=30, validators=[django.core.validators.MinValueValidator(30), workshop1.petstagram.validators.validate_only_letters])),
                ('profile_picture', models.ImageField(upload_to='')),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not ask', 'Do not ask')], max_length=10, null=True)),
            ],
        ),
    ]
