# Generated by Django 4.0.2 on 2022-02-06 16:17

import django.core.validators
from django.db import migrations, models
import workshop1.petstagram.validators


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0002_alter_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinValueValidator(2), workshop1.petstagram.validators.validate_only_letters]),
        ),
    ]
