# Generated by Django 4.0.2 on 2022-02-06 16:20

import django.core.validators
from django.db import migrations, models
import workshop1.petstagram.validators


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0003_alter_profile_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), workshop1.petstagram.validators.validate_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), workshop1.petstagram.validators.validate_only_letters]),
        ),
    ]
