# Generated by Django 4.0.2 on 2022-02-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0005_pet_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(),
        ),
    ]
