# Generated by Django 4.0.2 on 2022-02-14 12:45

from django.db import migrations, models
import workshop1.petstagram.validators


class Migration(migrations.Migration):

    dependencies = [
        ('petstagram', '0006_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.URLField(validators=[workshop1.petstagram.validators.max_size]),
        ),
    ]
