# Generated by Django 4.0.1 on 2022-01-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='work',
            field=models.CharField(max_length=21),
        ),
    ]
