# Generated by Django 4.0.1 on 2022-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario', '0002_employee_age_employee_first_name_employee_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
