# Generated by Django 4.0.1 on 2022-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario', '0005_employee_egn_alter_employee_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='egn',
            field=models.CharField(max_length=20, unique=True, verbose_name='EGN'),
        ),
    ]
