# Generated by Django 4.0.1 on 2022-01-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mario', '0008_remove_employee_egn'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='Sofia', max_length=20),
            preserve_default=False,
        ),
    ]
