# Generated by Django 4.0.1 on 2022-01-31 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mario', '0009_employee_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
    ]
